### ISSUE TITLE
Spamming a error message in console

### ISSUE THREAD

**Issue by Metalx69** [MalibuTechTeam/mbt_malisling#15]
Hi, everything seems to work fine, but my console is spamming error messages.
Using Ox inventory with ESX 1.8.5

![error](https://github.com/MalibuTechTeam/mbt_malisling/assets/55113394/94d07768-e81c-4b6e-81ed-5b6448821a9f)

**Comment by MalibuTechTeam** [comment]
Please, provide more information about how to reproduce this issue. Seems related to the scopes, also, turn on the ```MBT.Debugger``` to make it more easy understandable

**Comment by MalibuTechTeam** [comment]
Should be solved in 1.1.2
