### ISSUE TITLE
Jerry Can

### ISSUE THREAD

**Issue by KuMoNDev** [MalibuTechTeam/mbt_malisling#19]
if you add weapon_jerry can to weapons.lua and then get a jerry can and take it off your back to your hands it will drop the prop to the ground.

**Comment by MalibuTechTeam** [comment]
![image](https://github.com/MalibuTechTeam/mbt_malisling/assets/80293723/f8ad3ade-6c6b-4e3f-b42f-02c9834520b4)

I just tried it and it's not a bug, the jerrycan once used regularly returns to its place on the player!
