### ISSUE TITLE
Support for "Skills" Systems

### ISSUE THREAD

**Issue by JeyCraft** [MalibuTechTeam/mbt_malisling#5]
Just another Idea,

How about Support for Skill Systems. ( Like OT_Skills ) When your Shooting Level is Higher the Chance for Gun Jamming is lower.

**Comment by MalibuTechTeam** [comment]
We are working on our skill system for weapons, which will support it :)

**Comment by JeyCraft** [comment]
So, Support for Different Skill Systems will be Possible too?
