### ISSUE TITLE
Support for "EUP" Clothings

### ISSUE THREAD

**Issue by JeyCraft** [MalibuTechTeam/mbt_malisling#6]
Hey, it would be cool if the System could be better intigrated for EUP Clothings so Weapons will be on the positions on Leg Holsters or Breast holsters.

![image](https://github.com/MalibuTechTeam/mbt_malisling/assets/63811758/59d41bcd-3760-4247-8cd5-61807775d118)
![image](https://github.com/MalibuTechTeam/mbt_malisling/assets/63811758/3945d0c8-1f21-420c-9790-0159e0baf5d5)

**Comment by Kaanhehe** [comment]
The problem with your request is that you cant just ask a eup clothing piece where its weapon has to be, you would have to configure it yourself by just putting in the right coords so it lines up with the clothing. Also that is what this script support, it makes it easy for you to configure these coords
